default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight (Internal)"
  lane :internal do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      groups: ["Internal Testers"]
    )
  end

  desc "Deploy to TestFlight (External)"
  lane :beta do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      groups: ["External Testers"]
    )
  end

  desc "Deploy to App Store"
  lane :release do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    
    upload_to_app_store(
      skip_binary_upload: false,
      skip_screenshots: true,
      skip_metadata: true,
      force: true
    )
  end
end