default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'play.json'
    )
  end

  desc "Submit a new Beta to Play Store"
  lane :beta do
    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'play.json'
    )
  end

  desc "Submit a new Release to Play Store"
  lane :release do
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'play.json'
    )
  end
end