default_platform(:android)

platform :android do
  desc "Deploy to Internal Testing"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'play.json',
      release_status: 'completed'
      package_name: 'com.hoop.mobile'
    )
  end

  desc "Deploy to Beta Testing"
  lane :beta do
    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'play.json',
      release_status: 'completed'
      package_name: 'com.hoop.mobile'
    )
  end

  desc "Deploy to Production"
  lane :release do
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'play.json',
      release_status: 'completed'
      package_name: 'com.hoop.mobile'
    )
  end
end